src/lib/functions.js
test/functions-test.js

This ensures we are properly validating the hostname to not allow domains that are subdomains of other domains.

Fix vimeo URL check

---

src/lib/postmessage.js

Under some circumstances, for example with videojs, this method can be called while the `player.element.contentWindow` is already destroyed and this throws an exception;

fix(postmessage): safety check

---

src/lib/embed.js

Add support for the `background` in the iframe embed parameters
Fixes #170 .

support for the `background` parameter

---

README.md

Consistently use asterisk instead of hyphens to render markdown lists.

Consistently use asterisk instead of hyphens to render markdown lists

---

README.md

This change adds documentation for two new events `bufferstart` and `bufferend` surfaced in player.js
Fixes #211

Add documentation for bufferstart and bufferend

---

src/lib/embed.js
src/player.js

`vimeo-space` is no longer used as the responsive player embed code contains an enclosing div in all cases. Hence this conditional can be removed.

Remove resize conditional in embed.js

---

src/player.js

This change adds an additional check to look for window.Vimeo before checking for a player instance.
Fixes #238 .

Check for Vimeo object 

---

src/lib/embed.js
src/player.js

This PR gives users the ability to properly detect errors on player instantiation. We detect errors as follows:
`var player = new Vimeo.Player('made-in-ny', options);
player.ready().catch((error) => {
console.log('ERROR', error);
});
`
Before this change, a 403 (privacy settings error) wouldn't be caught. Now, we throw the error to allow devs to give their own visual feedback. This currently is using a CI link, which will be updated to production before being merged.  
Fixes https://github.com/vimeo/player.js/issues/165

Reject ready promise on 403

---

README.md

Removes the unmaintained link to Gitter from the README.

Remove Gitter Chat Link

---

src/player.js

This fixes the `remove()` method on IE.
Fixes #331

Fix remove() for IE

---

README.md
package.json
src/player.js
test/embed-test.js
test/helpers/browser-env.js
test/player-test.js
yarn.lock

This PR adds new getters that will return the `video.played`, `video.buffered` and `video.seekable` read-only properties.
These are `TimeRanges` objects originally but since they hold functions it's not possible to pass those objects via `postMessage`.
To get around this they are serialized as arrays of [start, end].
The `seeking` event is already added FYI.
Fixes #61

Add extra getters played, buffered, seekable

---

README.md
src/lib/embed.js

Just adding `dnt` to the available `oEmbedParameters` as this is something I need.
It is listed as an available player parameter here:
https://help.vimeo.com/hc/en-us/articles/360001494447-Using-Player-Parameters
I think this is straightforward enough that I don't need to add any tests as it seems to already be covered, but if there is anything else I need to do please let me know.
Thanks!

Add dnt to oEmbedParameters

---

src/lib/embed.js

Fixes #406
We no longer use the `domain` param to detect this.

Remove unused domain param

---

.eslintrc.js
src/lib/fullscreen.js
src/player.js

Fixes #584
This change adds fullscreen helpers to request and exit fullscreen, add and remove event listeners for `fullscreenchange`. If the w3c fullscreen API is available it will be used, if not the fullscreen methods will fallback to try and request the internal player fullscreen methods via postMessage. This is needed for iOS which goes fullscreen via the `<video>` element.

Add fullscreen lib for iframe

---

README.md
src/lib/embed.js

Adds the option to pass in the forthcoming `interactiveparams` option to the player, as well as updates documentation.

Add interactive params embed option

---

README.md
src/lib/embed.js

This fixes the `interactive_params` oEmbed option naming, which was originally entered as `interactiveparams`.

Fix interactive_params naming

---

.github/workflows/publish-package.yml

Follows GitHub docs on publishing to npm using yarn: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-using-yarn
Configures `scope` during setup node step, adds `--access=public` flag to publish step.
Hopefully fixes `error Couldn't publish package: "https://registry.npmjs.org/@vimeo%2fplayer: Not found"`

Use npm publish for deploy workflow

---

src/player.js

Throws a `TypeError` if a non-array argument is provided to `setColors`. This fixes a failing test that was on master.

Ensure setColors throws TypeError for non-array input

---

.github/workflows/pr-merge.yml

Uploads coverage to CodeCov for the master branch when a new PR is merged.

Upload test coverage on PR merge

---

README.md

Replaces references to the "Private" privacy setting with the "Unlisted" privacy setting when mentioning hash parameter requirements.

Refer to Unlisted privacy setting when mentioning required hash param

---

src/lib/embed.js
src/lib/functions.js
test/functions-test.js

Supports \*.videoji.hk and player.\*.videoji.hk domains as vimeo urls.

support *.videoji.hk domains as vimeo domains

---

README.md

Fixes the link to the `loadVideo` method docs in the Table of Contents.

Fix anchor link to loadVideo docs

---

README.md

This PR adds a "Dev Options" section with its first entry, the `prefer_mms` query param.

Document prefer_mms param
